package br.com.uem.sebo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiscoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscoAllPropertiesEquals(Disco expected, Disco actual) {
        assertDiscoAutoGeneratedPropertiesEquals(expected, actual);
        assertDiscoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscoAllUpdatablePropertiesEquals(Disco expected, Disco actual) {
        assertDiscoUpdatableFieldsEquals(expected, actual);
        assertDiscoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscoAutoGeneratedPropertiesEquals(Disco expected, Disco actual) {
        assertThat(actual)
            .as("Verify Disco auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscoUpdatableFieldsEquals(Disco expected, Disco actual) {
        assertThat(actual)
            .as("Verify Disco relevant properties")
            .satisfies(a -> assertThat(a.getTipoMidia()).as("check tipoMidia").isEqualTo(expected.getTipoMidia()))
            .satisfies(a -> assertThat(a.getDuracaoMinutos()).as("check duracaoMinutos").isEqualTo(expected.getDuracaoMinutos()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscoUpdatableRelationshipsEquals(Disco expected, Disco actual) {
        // empty method
    }
}
