package br.com.uem.sebo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmprestimoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmprestimoAllPropertiesEquals(Emprestimo expected, Emprestimo actual) {
        assertEmprestimoAutoGeneratedPropertiesEquals(expected, actual);
        assertEmprestimoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmprestimoAllUpdatablePropertiesEquals(Emprestimo expected, Emprestimo actual) {
        assertEmprestimoUpdatableFieldsEquals(expected, actual);
        assertEmprestimoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmprestimoAutoGeneratedPropertiesEquals(Emprestimo expected, Emprestimo actual) {
        assertThat(actual)
            .as("Verify Emprestimo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmprestimoUpdatableFieldsEquals(Emprestimo expected, Emprestimo actual) {
        assertThat(actual)
            .as("Verify Emprestimo relevant properties")
            .satisfies(a -> assertThat(a.getDataEmprestimo()).as("check dataEmprestimo").isEqualTo(expected.getDataEmprestimo()))
            .satisfies(a ->
                assertThat(a.getDataPrevistaDevolucao()).as("check dataPrevistaDevolucao").isEqualTo(expected.getDataPrevistaDevolucao())
            )
            .satisfies(a -> assertThat(a.getDataDevolucao()).as("check dataDevolucao").isEqualTo(expected.getDataDevolucao()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmprestimoUpdatableRelationshipsEquals(Emprestimo expected, Emprestimo actual) {
        assertThat(actual)
            .as("Verify Emprestimo relationships")
            .satisfies(a -> assertThat(a.getUsuario()).as("check usuario").isEqualTo(expected.getUsuario()))
            .satisfies(a -> assertThat(a.getItens()).as("check itens").isEqualTo(expected.getItens()));
    }
}
