package br.com.uem.sebo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemAllPropertiesEquals(Item expected, Item actual) {
        assertItemAutoGeneratedPropertiesEquals(expected, actual);
        assertItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemAllUpdatablePropertiesEquals(Item expected, Item actual) {
        assertItemUpdatableFieldsEquals(expected, actual);
        assertItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemAutoGeneratedPropertiesEquals(Item expected, Item actual) {
        assertThat(actual)
            .as("Verify Item auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemUpdatableFieldsEquals(Item expected, Item actual) {
        assertThat(actual)
            .as("Verify Item relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getAno()).as("check ano").isEqualTo(expected.getAno()))
            .satisfies(a -> assertThat(a.getGenero()).as("check genero").isEqualTo(expected.getGenero()))
            .satisfies(a -> assertThat(a.getAutorArtista()).as("check autorArtista").isEqualTo(expected.getAutorArtista()))
            .satisfies(a -> assertThat(a.getDisponibilidade()).as("check disponibilidade").isEqualTo(expected.getDisponibilidade()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemUpdatableRelationshipsEquals(Item expected, Item actual) {
        assertThat(actual)
            .as("Verify Item relationships")
            .satisfies(a -> assertThat(a.getEmprestimos()).as("check emprestimos").isEqualTo(expected.getEmprestimos()))
            .satisfies(a -> assertThat(a.getVendas()).as("check vendas").isEqualTo(expected.getVendas()));
    }
}
