package br.com.uem.sebo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LivroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivroAllPropertiesEquals(Livro expected, Livro actual) {
        assertLivroAutoGeneratedPropertiesEquals(expected, actual);
        assertLivroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivroAllUpdatablePropertiesEquals(Livro expected, Livro actual) {
        assertLivroUpdatableFieldsEquals(expected, actual);
        assertLivroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivroAutoGeneratedPropertiesEquals(Livro expected, Livro actual) {
        assertThat(actual)
            .as("Verify Livro auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivroUpdatableFieldsEquals(Livro expected, Livro actual) {
        assertThat(actual)
            .as("Verify Livro relevant properties")
            .satisfies(a -> assertThat(a.getIsbn()).as("check isbn").isEqualTo(expected.getIsbn()))
            .satisfies(a -> assertThat(a.getEditora()).as("check editora").isEqualTo(expected.getEditora()))
            .satisfies(a -> assertThat(a.getNumeroPaginas()).as("check numeroPaginas").isEqualTo(expected.getNumeroPaginas()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivroUpdatableRelationshipsEquals(Livro expected, Livro actual) {
        // empty method
    }
}
