package br.com.uem.sebo.domain;

import static br.com.uem.sebo.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VendaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendaAllPropertiesEquals(Venda expected, Venda actual) {
        assertVendaAutoGeneratedPropertiesEquals(expected, actual);
        assertVendaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendaAllUpdatablePropertiesEquals(Venda expected, Venda actual) {
        assertVendaUpdatableFieldsEquals(expected, actual);
        assertVendaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendaAutoGeneratedPropertiesEquals(Venda expected, Venda actual) {
        assertThat(actual)
            .as("Verify Venda auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendaUpdatableFieldsEquals(Venda expected, Venda actual) {
        assertThat(actual)
            .as("Verify Venda relevant properties")
            .satisfies(a -> assertThat(a.getDataVenda()).as("check dataVenda").isEqualTo(expected.getDataVenda()))
            .satisfies(a -> assertThat(a.getValor()).as("check valor").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValor()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendaUpdatableRelationshipsEquals(Venda expected, Venda actual) {
        assertThat(actual)
            .as("Verify Venda relationships")
            .satisfies(a -> assertThat(a.getUsuario()).as("check usuario").isEqualTo(expected.getUsuario()))
            .satisfies(a -> assertThat(a.getItens()).as("check itens").isEqualTo(expected.getItens()));
    }
}
